FROM node:10

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./nsf-demo-stock-advisor-nodejs/package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production
# Bundle app source

RUN npm install request@2.81.0

COPY . .

EXPOSE 9002
CMD [ "node", "demo.js" ]